spring.datasource.url=jdbc:mysql://118.89.62.40:3306/ignai_hackthon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=admin
spring.datasource.password=MEm4hpf5yDntDif2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=hackathon-server
mybatis.configuration.map-underscore-to-camel-case=true
